### ISSUE TITLE
`SpawnWeaponsWarhead`: add support for inaccuracy

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#452] opened 2023-08-31 20:09 UTC
Add support for inaccuracy, similar to how `CreateEffectWarhead` does it.

**Comment by michal-mad** [comment] 2023-09-02 21:41
@michaeldgg2 is this a duplicate of #432 ?

**Comment by michaeldgg2** [comment] 2023-09-15 12:17
Implemented in 44299bad58688ef8010270804e488e8ba750e236

**Closed as completed** 2023-09-15 12:17 UTC
Labels: enhancement
